### PR TITLE
Added module name to beginning of example filename and updated docs to reflect this

### PR DESCRIPTION
**Pull request by evaherrada**

### CODE REVIEW

**Comment by evaherrada** [comment]
@makermelissa Seems like it might be a similar bug to the one encountered during pycon

**Comment by makermelissa** [comment]
Yeah, I'm re-running it to see if that helps.

**Review by makermelissa — CHANGES_REQUESTED** [review]
Can you update the example to have pylint disable messages around the offending code?
```
#pylint: disable-msg=no-member
buzzer = pulseio.PWMOut(BUZZER_PIN, duty_cycle=TONE_OFF_DUTY, frequency=440,
                        variable_frequency=True)
#pylint: enable-msg=no-member
```

**Review by makermelissa — APPROVED** [review]

**Comment by makermelissa** [comment]
Thanks!

**Pull request merged**
